### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by danieltomasku** [danieltomasku/ok-studio-website-dynamic#10]
Implement Google Analytics on the site.
- [x] Ensure that it's tracking each route change as an actual page view
- [x] Ensure that we can track custom events like click events

**Comment by antonlegoo** [comment]
Added [vue-analytics](https://github.com/MatteoGabriele/vue-analytics/tree/b2d88c0a15c4afc989e70b5ce1b6d29faae0d29a) and tested via the [debug feature](https://github.com/MatteoGabriele/vue-analytics/blob/b2d88c0a15c4afc989e70b5ce1b6d29faae0d29a/docs/debug.md) that page tracking is working (I don't have access to their GA account so that was the only way to verify).

[Event tracking](https://github.com/MatteoGabriele/vue-analytics/blob/b2d88c0a15c4afc989e70b5ce1b6d29faae0d29a/docs/event-tracking.md) is also possible.
