### ISSUE TITLE
Handle Form Sending

### ISSUE THREAD

**Issue by danieltomasku** [danieltomasku/ok-studio-website-dynamic#19]
There are a couple places where the form shows up:
- Homepage with the "Say hello" CTA that opens up a modal
- In the Footer with the "Stay Updated" form input on every page
- The Workshops page also has a button that opens up the same form modal as the Homepage

Form should send an email with form content to OK Studio's email address.

**Comment by antonlegoo** [comment]
@danieltomasku  Ok, so I did some testing and indeed each page still needs to be verified. The problem with that being if someone were the first to sign up from the footer form of a dynamically created page, like a new project, it will have to be verified before sending. OK could make it part of their process to verify every time they create a page, but thats not very elegant.

I did some searching for some alternatives. Turns out netlify has its own [forms feature](https://www.netlify.com/docs/form-handling/)! It looks really promising however there's one hitch: its free up to 100 submissions per month, after that they **automatically bump you to a paid tier**. That is pretty presumptuous in my opinion. If we went with this approach, OK would have to be cool with the risk of bumping tiers if they get over 100 submissions.

I've integrated the netlify form in my working branch, so you can test it [here](https://5c3b94d94b2e7e000836aa91--ok-website-cms.netlify.com/) and see the form submissions [here](https://app.netlify.com/sites/ok-website-cms/forms). For now, I only have the **Home and Footer forms** working. And right now the submissions collect in the Forms section, however we can setup [form notifications](https://app.netlify.com/sites/ok-website-cms/settings/forms#form-notifications) to forward them to an email or even a slack channel.

**Comment by danieltomasku** [comment]
@antonlegoo this sounds great! thanks for looking into this. let's make sure to test the e-mail notification feature to make sure that works as expected. I want to make sure that it includes the content of the form in that e-mail notification and doesn't just notify that there's a notification.

As for the 100 submissions per month limit: I'm not too worried that they'll reach that limit. We can keep an eye on it and if it ever creeps up near 100 we can talk about a paid solution.

If you want to go ahead and test that e-mail notification feature (we could also test the Slack notification as well!) and then make a PR that would be great! 😃

**Comment by antonlegoo** [comment]
Just tested the email notification, it does indeed send the entire content of the form:

![image](https://user-images.githubusercontent.com/1424526/51091098-a678fe00-173a-11e9-8d8b-be5743eeef48.png)

Not sure how to test for Slack integration as I don't own any Slacks. @danieltomasku if you do, feel free to try it out.
